name: Lint on pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  full_ci:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-18.04
    env:
      DETA_SDK_TEST_BASE_NAME: ${{secrets.DETA_SDK_TEST_BASE_NAME}}
      DETA_SDK_TEST_PROJECT_KEY: ${{secrets.DETA_SDK_TEST_PROJECT_KEY}}
      DETA_SDK_TEST_ENDPOINT: ${{secrets.DETA_SDK_TEST_ENDPOINT}}
    steps:
      # Get the code into the container
      - name: Checkout
        uses: actions/checkout@v2
      # Lint code
      #- name: Run golangci-lint
      #  uses: golangci/golangci-lint-action@v2.5.2
      # Test the code
      - name: Test code
        run: go test -json ./... > test.json
      - name: Print results
        run: cat test.json
      # Display linting info
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.3.0
        with:
          test-results: test.json